services:
  # Single container with scheduler and Python app
  daily-it-news:
    build: .
    container_name: daily-it-news
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./scheduler:/app/scheduler
    environment:
      - TZ=Europe/Stockholm
    # Run the scheduler directly
    command: [ "bash", "/app/scheduler/scheduler.sh" ]
